package com.sistema_contable.vista;

import java.awt.BorderLayout;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import com.sistema_contable.vista.cliente.ListaCliente;
import com.sistema_contable.vista.general.General;
import com.sistema_contable.vista.pers.Personalizado;

public class Inicio extends javax.swing.JFrame {
    
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form Inicio
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panel_izquierdo = new javax.swing.JPanel();
        lb_titulo_principal = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btn_home = new javax.swing.JButton();
        btn_busq_pers = new javax.swing.JButton();
        btn_busq_gnrl = new javax.swing.JButton();
        btn_cliente_admin = new javax.swing.JButton();
        panel_superior = new javax.swing.JPanel();
        lb_titulo_superior = new javax.swing.JLabel();
        panel_central = new javax.swing.JPanel();
        lb_bienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(239, 239, 239));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_izquierdo.setBackground(new java.awt.Color(57, 50, 58));

        lb_titulo_principal.setBackground(new java.awt.Color(246, 183, 32));
        lb_titulo_principal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titulo_principal.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo_principal.setText("REVICONT E.I.R.L.");

        separador.setBackground(new java.awt.Color(45, 170, 226));
        separador.setForeground(new java.awt.Color(45, 170, 226));
        separador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        separador.setPreferredSize(new java.awt.Dimension(100, 15));
        separador.setRequestFocusEnabled(false);

        btn_home.setBackground(new java.awt.Color(57, 50, 58));
        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setBorder(null);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_busq_pers.setBackground(new java.awt.Color(57, 50, 58));
        btn_busq_pers.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_busq_pers.setForeground(new java.awt.Color(255, 255, 255));
        btn_busq_pers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btn_busq_pers.setText("Personalizado");
        btn_busq_pers.setBorder(null);
        btn_busq_pers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busq_persActionPerformed(evt);
            }
        });

        btn_busq_gnrl.setBackground(new java.awt.Color(57, 50, 58));
        btn_busq_gnrl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_busq_gnrl.setForeground(new java.awt.Color(255, 255, 255));
        btn_busq_gnrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        btn_busq_gnrl.setText("General");
        btn_busq_gnrl.setBorder(null);
        btn_busq_gnrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busq_gnrlActionPerformed(evt);
            }
        });

        btn_cliente_admin.setBackground(new java.awt.Color(57, 50, 58));
        btn_cliente_admin.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_cliente_admin.setForeground(new java.awt.Color(255, 255, 255));
        btn_cliente_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ClienteOficial.png"))); // NOI18N
        btn_cliente_admin.setText("Clientes");
        btn_cliente_admin.setBorder(null);
        btn_cliente_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cliente_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_izquierdoLayout = new javax.swing.GroupLayout(panel_izquierdo);
        panel_izquierdo.setLayout(panel_izquierdoLayout);
        panel_izquierdoLayout.setHorizontalGroup(
            panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                .addGroup(panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_izquierdoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(separador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_izquierdoLayout.createSequentialGroup()
                        .addGroup(panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_busq_gnrl)
                                    .addComponent(btn_busq_pers)
                                    .addComponent(btn_home)
                                    .addComponent(btn_cliente_admin)))
                            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lb_titulo_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_izquierdoLayout.setVerticalGroup(
            panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lb_titulo_principal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_home)
                .addGap(37, 37, 37)
                .addComponent(btn_busq_pers)
                .addGap(36, 36, 36)
                .addComponent(btn_busq_gnrl)
                .addGap(30, 30, 30)
                .addComponent(btn_cliente_admin)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        panelPrincipal.add(panel_izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 520));

        panel_superior.setBackground(new java.awt.Color(254, 255, 255));

        lb_titulo_superior.setBackground(new java.awt.Color(15, 53, 92));
        lb_titulo_superior.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lb_titulo_superior.setForeground(new java.awt.Color(79, 79, 81));
        lb_titulo_superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Revicont.png"))); // NOI18N
        lb_titulo_superior.setText("Gestion de Vencimientos IR");

        javax.swing.GroupLayout panel_superiorLayout = new javax.swing.GroupLayout(panel_superior);
        panel_superior.setLayout(panel_superiorLayout);
        panel_superiorLayout.setHorizontalGroup(
            panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_superiorLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(lb_titulo_superior)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        panel_superiorLayout.setVerticalGroup(
            panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_superiorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_titulo_superior)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelPrincipal.add(panel_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 690, 70));

        panel_central.setBackground(new java.awt.Color(204, 204, 204));
        panel_central.setForeground(new java.awt.Color(51, 51, 51));

        lb_bienvenida.setBackground(new java.awt.Color(239, 239, 239));
        lb_bienvenida.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lb_bienvenida.setForeground(new java.awt.Color(51, 51, 51));
        lb_bienvenida.setText("Bienvenido al sistema...");

        javax.swing.GroupLayout panel_centralLayout = new javax.swing.GroupLayout(panel_central);
        panel_central.setLayout(panel_centralLayout);
        panel_centralLayout.setHorizontalGroup(
            panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centralLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(lb_bienvenida)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        panel_centralLayout.setVerticalGroup(
            panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centralLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(lb_bienvenida)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        panelPrincipal.add(panel_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 690, 450));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_busq_gnrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busq_gnrlActionPerformed
        General g = new General();
        g.setVisible(true);
        g.setSize(690, 450);
        g.setLocation(0, 0);
        panel_central.removeAll();
        panel_central.add(g, BorderLayout.CENTER);
        panel_central.revalidate();
        panel_central.repaint();
    }//GEN-LAST:event_btn_busq_gnrlActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        panel_central.removeAll();
        panel_central.setLayout(new GroupLayout(panel_central));
        lb_bienvenida.setVisible(true);
        panel_central.add(lb_bienvenida);
        panel_central.revalidate();
        panel_central.repaint();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_busq_persActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busq_persActionPerformed
        Personalizado p = new Personalizado();
        lb_bienvenida.setVisible(false);
        p.setVisible(true);
        p.setSize(690, 450);
        p.setLocation(0, 0);
        panel_central.removeAll();
        panel_central.add(p, BorderLayout.CENTER);
        panel_central.revalidate();
        panel_central.repaint();
    }//GEN-LAST:event_btn_busq_persActionPerformed

    private void btn_cliente_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cliente_adminActionPerformed
        ListaCliente c = new ListaCliente();
        lb_bienvenida.setVisible(false);
        c.setVisible(true);
        c.setSize(690, 450);
        c.setLocation(0, 0);
        panel_central.removeAll();
        panel_central.add(c, BorderLayout.CENTER);
        panel_central.revalidate();
        panel_central.repaint();
    }//GEN-LAST:event_btn_cliente_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_busq_gnrl;
    private javax.swing.JButton btn_busq_pers;
    private javax.swing.JButton btn_cliente_admin;
    private javax.swing.JButton btn_home;
    private javax.swing.JLabel lb_bienvenida;
    private javax.swing.JLabel lb_titulo_principal;
    private javax.swing.JLabel lb_titulo_superior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panel_central;
    private javax.swing.JPanel panel_izquierdo;
    private javax.swing.JPanel panel_superior;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
