package com.sistema_contable.vista.cliente;

import com.sistema_contable.Implements.ClienteDaoImpl;
import com.sistema_contable.interfaces.IClienteDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.sistema_contable.model.Cliente;

public class ListaCliente extends javax.swing.JPanel {

    IClienteDao CDao = new ClienteDaoImpl();
    Cliente cl = new Cliente();

    public ListaCliente() {
        initComponents();
        CargarClientes();
    }

    public void CargarClientes(){
        List<Cliente> lista = CDao.listar();
        DefaultTableModel table = (DefaultTableModel) tbl_clientes.getModel();
        table.setNumRows(0);
        for (Cliente c : lista) {
            Object[] rowData = {
                c.getIdCliente(),
                c.getRUC(),
                c.getNombre()
            };
            table.addRow(rowData);
        }
        tbl_clientes.setModel(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_agregar1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(690, 450));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tbl_clientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NOMBRE", "RUC"
            }
        ));
        jScrollPane1.setViewportView(tbl_clientes);
        if (tbl_clientes.getColumnModel().getColumnCount() > 0) {
            tbl_clientes.getColumnModel().getColumn(0).setMinWidth(103);
            tbl_clientes.getColumnModel().getColumn(0).setMaxWidth(103);
            tbl_clientes.getColumnModel().getColumn(1).setMinWidth(35);
            tbl_clientes.getColumnModel().getColumn(1).setMaxWidth(35);
        }

        btn_agregar.setBackground(new java.awt.Color(3, 187, 133));
        btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(204, 255, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(225, 8, 8));
        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_agregar1.setBackground(new java.awt.Color(0, 123, 255));
        btn_agregar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agregar1.setForeground(new java.awt.Color(0, 0, 0));
        btn_agregar1.setText("Recargar");
        btn_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_agregar1)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_agregar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        AgregarCliente a = new AgregarCliente();
        a.setVisible(true);
        a.setSize(463, 302);
        a.setLocation(0, 0);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (tbl_clientes.getRowCount()>0) {
            if (tbl_clientes.getSelectedRow() != -1) {
                int idCliente = Integer.parseInt(tbl_clientes.getValueAt(tbl_clientes.getSelectedRow(),0).toString());
                int res = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar este cliente?");
                if (JOptionPane.OK_OPTION == res) {
                    cl.setIdCliente(idCliente);
                    CDao.eliminar(cl);
                    JOptionPane.showMessageDialog(null, "Cliente Eliminado :(",
                            "INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                    CargarClientes();
                }else{
                     JOptionPane.showMessageDialog(null, "Operacion Cancelada",
                            "INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar1ActionPerformed
        CargarClientes();
        JOptionPane.showMessageDialog(null, "Carga completa :)",
                "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_agregar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregar1;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_clientes;
    // End of variables declaration//GEN-END:variables
}
