package com.sistema_contable.vista.pers;

import com.sistema_contable.Implements.ClienteDaoImpl;
import com.sistema_contable.Implements.VencimientosDaoImpl;
import com.sistema_contable.interfaces.IClienteDao;
import com.sistema_contable.interfaces.IVencimientosDao;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import com.sistema_contable.model.Cliente;
import com.sistema_contable.model.PLE;
import com.sistema_contable.model.Vencimientos;

public class Personalizado extends javax.swing.JPanel {

    int idCliente = 0;
    int idVencimiento = 0;

    public Personalizado() {
        initComponents();
        guardarTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_print = new javax.swing.JPanel();
        pnl_ene = new javax.swing.JPanel();
        lb_ene = new javax.swing.JLabel();
        txt_ene = new javax.swing.JLabel();
        pnl_feb = new javax.swing.JPanel();
        lb_feb = new javax.swing.JLabel();
        txt_feb = new javax.swing.JLabel();
        pnl_mar = new javax.swing.JPanel();
        lb_mar = new javax.swing.JLabel();
        txt_mar = new javax.swing.JLabel();
        pnl_abr = new javax.swing.JPanel();
        lb_abr = new javax.swing.JLabel();
        txt_abr = new javax.swing.JLabel();
        pnl_may = new javax.swing.JPanel();
        lb_may = new javax.swing.JLabel();
        txt_may = new javax.swing.JLabel();
        pnl_jun = new javax.swing.JPanel();
        lb_jun = new javax.swing.JLabel();
        txt_jun = new javax.swing.JLabel();
        pnl_jul = new javax.swing.JPanel();
        lb_jul = new javax.swing.JLabel();
        txt_jul = new javax.swing.JLabel();
        pnl_ago = new javax.swing.JPanel();
        lb_ago = new javax.swing.JLabel();
        txt_ago = new javax.swing.JLabel();
        pnl_sep = new javax.swing.JPanel();
        lb_set = new javax.swing.JLabel();
        txt_set = new javax.swing.JLabel();
        pnl_oct = new javax.swing.JPanel();
        lb_oct = new javax.swing.JLabel();
        txt_oct = new javax.swing.JLabel();
        pnl_nov = new javax.swing.JPanel();
        lb_nov = new javax.swing.JLabel();
        txt_nov = new javax.swing.JLabel();
        pnl_dic = new javax.swing.JPanel();
        lb_dic = new javax.swing.JLabel();
        txt_dic = new javax.swing.JLabel();
        lb_ruc = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        venc_box = new javax.swing.JComboBox<>();
        año_select = new com.toedter.calendar.JYearChooser();
        pnl_action = new javax.swing.JPanel();
        btn_buscar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(690, 450));

        pnl_print.setBackground(new java.awt.Color(204, 204, 204));

        pnl_ene.setBackground(new java.awt.Color(153, 153, 153));
        pnl_ene.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_ene.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_ene.setForeground(new java.awt.Color(0, 0, 0));
        lb_ene.setText("Ene-20** :");

        txt_ene.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_ene.setForeground(new java.awt.Color(0, 0, 0));
        txt_ene.setText("***ENERO**");

        javax.swing.GroupLayout pnl_eneLayout = new javax.swing.GroupLayout(pnl_ene);
        pnl_ene.setLayout(pnl_eneLayout);
        pnl_eneLayout.setHorizontalGroup(
            pnl_eneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_eneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_ene)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_eneLayout.setVerticalGroup(
            pnl_eneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_eneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_eneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ene)
                    .addComponent(txt_ene))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_feb.setBackground(new java.awt.Color(153, 153, 153));
        pnl_feb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_feb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_feb.setForeground(new java.awt.Color(0, 0, 0));
        lb_feb.setText("Feb-20** :");

        txt_feb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_feb.setForeground(new java.awt.Color(0, 0, 0));
        txt_feb.setText("***FEBRERO***");

        javax.swing.GroupLayout pnl_febLayout = new javax.swing.GroupLayout(pnl_feb);
        pnl_feb.setLayout(pnl_febLayout);
        pnl_febLayout.setHorizontalGroup(
            pnl_febLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_febLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_feb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_feb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_febLayout.setVerticalGroup(
            pnl_febLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_febLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_febLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_feb)
                    .addComponent(txt_feb))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_mar.setBackground(new java.awt.Color(153, 153, 153));
        pnl_mar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_mar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_mar.setForeground(new java.awt.Color(0, 0, 0));
        lb_mar.setText("Mar-20** :");

        txt_mar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_mar.setForeground(new java.awt.Color(0, 0, 0));
        txt_mar.setText("***MARZO***");

        javax.swing.GroupLayout pnl_marLayout = new javax.swing.GroupLayout(pnl_mar);
        pnl_mar.setLayout(pnl_marLayout);
        pnl_marLayout.setHorizontalGroup(
            pnl_marLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_marLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_mar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_mar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_marLayout.setVerticalGroup(
            pnl_marLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_marLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_marLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mar)
                    .addComponent(txt_mar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_abr.setBackground(new java.awt.Color(153, 153, 153));
        pnl_abr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_abr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_abr.setForeground(new java.awt.Color(0, 0, 0));
        lb_abr.setText("Abr-20** :");

        txt_abr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_abr.setForeground(new java.awt.Color(0, 0, 0));
        txt_abr.setText("***ABRIL***");

        javax.swing.GroupLayout pnl_abrLayout = new javax.swing.GroupLayout(pnl_abr);
        pnl_abr.setLayout(pnl_abrLayout);
        pnl_abrLayout.setHorizontalGroup(
            pnl_abrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_abrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_abr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_abr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_abrLayout.setVerticalGroup(
            pnl_abrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_abrLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnl_abrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_abr)
                    .addComponent(txt_abr))
                .addContainerGap())
        );

        pnl_may.setBackground(new java.awt.Color(153, 153, 153));
        pnl_may.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_may.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_may.setForeground(new java.awt.Color(0, 0, 0));
        lb_may.setText("May-20** :");

        txt_may.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_may.setForeground(new java.awt.Color(0, 0, 0));
        txt_may.setText("***MAYO***");

        javax.swing.GroupLayout pnl_mayLayout = new javax.swing.GroupLayout(pnl_may);
        pnl_may.setLayout(pnl_mayLayout);
        pnl_mayLayout.setHorizontalGroup(
            pnl_mayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_may)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_may, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_mayLayout.setVerticalGroup(
            pnl_mayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_mayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_may)
                    .addComponent(txt_may))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_jun.setBackground(new java.awt.Color(153, 153, 153));
        pnl_jun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_jun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_jun.setForeground(new java.awt.Color(0, 0, 0));
        lb_jun.setText("Jun-20** :");

        txt_jun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_jun.setForeground(new java.awt.Color(0, 0, 0));
        txt_jun.setText("***JUNIO***");

        javax.swing.GroupLayout pnl_junLayout = new javax.swing.GroupLayout(pnl_jun);
        pnl_jun.setLayout(pnl_junLayout);
        pnl_junLayout.setHorizontalGroup(
            pnl_junLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_junLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_jun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_jun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_junLayout.setVerticalGroup(
            pnl_junLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_junLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_junLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_jun)
                    .addComponent(txt_jun))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_jul.setBackground(new java.awt.Color(153, 153, 153));
        pnl_jul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_jul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_jul.setForeground(new java.awt.Color(0, 0, 0));
        lb_jul.setText("Jul-20** :");

        txt_jul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_jul.setForeground(new java.awt.Color(0, 0, 0));
        txt_jul.setText("***JULIO***");

        javax.swing.GroupLayout pnl_julLayout = new javax.swing.GroupLayout(pnl_jul);
        pnl_jul.setLayout(pnl_julLayout);
        pnl_julLayout.setHorizontalGroup(
            pnl_julLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_julLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_jul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_jul, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_julLayout.setVerticalGroup(
            pnl_julLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_julLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnl_julLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_jul)
                    .addComponent(txt_jul))
                .addContainerGap())
        );

        pnl_ago.setBackground(new java.awt.Color(153, 153, 153));
        pnl_ago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_ago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_ago.setForeground(new java.awt.Color(0, 0, 0));
        lb_ago.setText("Ago-20** :");

        txt_ago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_ago.setForeground(new java.awt.Color(0, 0, 0));
        txt_ago.setText("***AGOSTO***");

        javax.swing.GroupLayout pnl_agoLayout = new javax.swing.GroupLayout(pnl_ago);
        pnl_ago.setLayout(pnl_agoLayout);
        pnl_agoLayout.setHorizontalGroup(
            pnl_agoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_ago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ago, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_agoLayout.setVerticalGroup(
            pnl_agoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_agoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ago)
                    .addComponent(txt_ago))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_sep.setBackground(new java.awt.Color(153, 153, 153));
        pnl_sep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_set.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_set.setForeground(new java.awt.Color(0, 0, 0));
        lb_set.setText("Set-20** :");

        txt_set.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_set.setForeground(new java.awt.Color(0, 0, 0));
        txt_set.setText("***SEPTIEMBRE***");

        javax.swing.GroupLayout pnl_sepLayout = new javax.swing.GroupLayout(pnl_sep);
        pnl_sep.setLayout(pnl_sepLayout);
        pnl_sepLayout.setHorizontalGroup(
            pnl_sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_set)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_set, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_sepLayout.setVerticalGroup(
            pnl_sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_set)
                    .addComponent(txt_set))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_oct.setBackground(new java.awt.Color(153, 153, 153));
        pnl_oct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_oct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_oct.setForeground(new java.awt.Color(0, 0, 0));
        lb_oct.setText("Oct-20** :");

        txt_oct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_oct.setForeground(new java.awt.Color(0, 0, 0));
        txt_oct.setText("***OCTUBRE***");

        javax.swing.GroupLayout pnl_octLayout = new javax.swing.GroupLayout(pnl_oct);
        pnl_oct.setLayout(pnl_octLayout);
        pnl_octLayout.setHorizontalGroup(
            pnl_octLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_octLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_oct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_oct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_octLayout.setVerticalGroup(
            pnl_octLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_octLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_octLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oct)
                    .addComponent(txt_oct))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_nov.setBackground(new java.awt.Color(153, 153, 153));
        pnl_nov.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_nov.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_nov.setForeground(new java.awt.Color(0, 0, 0));
        lb_nov.setText("Nov-20** :");

        txt_nov.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_nov.setForeground(new java.awt.Color(0, 0, 0));
        txt_nov.setText("***NOVIEMBRE***");

        javax.swing.GroupLayout pnl_novLayout = new javax.swing.GroupLayout(pnl_nov);
        pnl_nov.setLayout(pnl_novLayout);
        pnl_novLayout.setHorizontalGroup(
            pnl_novLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_novLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_nov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nov, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_novLayout.setVerticalGroup(
            pnl_novLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_novLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_novLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nov)
                    .addComponent(txt_nov))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnl_dic.setBackground(new java.awt.Color(153, 153, 153));
        pnl_dic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_dic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_dic.setForeground(new java.awt.Color(0, 0, 0));
        lb_dic.setText("Dic-20** :");

        txt_dic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_dic.setForeground(new java.awt.Color(0, 0, 0));
        txt_dic.setText("***DICIEMBRE***");

        javax.swing.GroupLayout pnl_dicLayout = new javax.swing.GroupLayout(pnl_dic);
        pnl_dic.setLayout(pnl_dicLayout);
        pnl_dicLayout.setHorizontalGroup(
            pnl_dicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_dic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_dic, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_dicLayout.setVerticalGroup(
            pnl_dicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_dicLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnl_dicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dic)
                    .addComponent(txt_dic))
                .addContainerGap())
        );

        lb_ruc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_ruc.setForeground(new java.awt.Color(0, 0, 0));
        lb_ruc.setText("RUC :");

        txt_ruc.setBackground(new java.awt.Color(255, 255, 255));
        txt_ruc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        venc_box.setBackground(new java.awt.Color(255, 255, 255));
        venc_box.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        venc_box.setForeground(new java.awt.Color(0, 0, 0));
        venc_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOGER VENC", "IMPUESTOS", "PLE", "AMBOS" }));
        venc_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venc_boxActionPerformed(evt);
            }
        });

        año_select.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_printLayout = new javax.swing.GroupLayout(pnl_print);
        pnl_print.setLayout(pnl_printLayout);
        pnl_printLayout.setHorizontalGroup(
            pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_printLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_printLayout.createSequentialGroup()
                        .addComponent(lb_ruc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(venc_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(año_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_printLayout.createSequentialGroup()
                        .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnl_jun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_mar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_feb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_ene, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_abr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_may, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnl_oct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnl_jul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_ago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_sep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_dic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
        pnl_printLayout.setVerticalGroup(
            pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_printLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_ruc)
                        .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(venc_box, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(año_select, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_printLayout.createSequentialGroup()
                        .addComponent(pnl_ene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_feb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_mar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_abr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_may, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_jun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_printLayout.createSequentialGroup()
                        .addComponent(pnl_jul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_ago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_sep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_oct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_dic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pnl_action.setBackground(new java.awt.Color(204, 204, 204));

        btn_buscar.setBackground(new java.awt.Color(242, 242, 242));
        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 0, 0));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(24, 115, 48));
        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpiar.png"))); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setBorderPainted(false);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(102, 102, 102));
        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_print.setForeground(new java.awt.Color(0, 0, 0));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora .png"))); // NOI18N
        btn_print.setText("Imprimir");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_actionLayout = new javax.swing.GroupLayout(pnl_action);
        pnl_action.setLayout(pnl_actionLayout);
        pnl_actionLayout.setHorizontalGroup(
            pnl_actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actionLayout.createSequentialGroup()
                .addComponent(btn_buscar)
                .addGap(18, 18, 18)
                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_print))
        );
        pnl_actionLayout.setVerticalGroup(
            pnl_actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_buscar)
                .addComponent(btn_limpiar)
                .addComponent(btn_print))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pnl_print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnl_action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarTexto() {
        txt_ene.setName(txt_ene.getText());
        txt_feb.setName(txt_feb.getText());
        txt_mar.setName(txt_mar.getText());
        txt_abr.setName(txt_abr.getText());
        txt_may.setName(txt_may.getText());
        txt_jun.setName(txt_jun.getText());
        txt_jul.setName(txt_jul.getText());
        txt_ago.setName(txt_ago.getText());
        txt_set.setName(txt_set.getText());
        txt_oct.setName(txt_oct.getText());
        txt_nov.setName(txt_nov.getText());
        txt_dic.setName(txt_dic.getText());
    }

    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            String ruc = txt_ruc.getText();
            if (ruc.isEmpty()) {
                mostrarMensaje("Ingrese el RUC");
                return;
            }
//            int ultimodigito=ruc.charAt(ruc.length()-1)-'0'; NO TOCAR
            IClienteDao CDao = new ClienteDaoImpl();
            Cliente cliente = CDao.BuscarPorRUC(ruc);
            if (cliente == null) {
                mostrarMensaje("Cliente no registrado");
            } else {
                this.idCliente = cliente.getIdCliente();
                IVencimientosDao VDao = new VencimientosDaoImpl();
                int año = (int) año_select.getValue();
                String tipo = venc_box.getSelectedItem().toString();
                Vencimientos v = VDao.buscarPorRUC(ruc, año, tipo);
                if (v == null) {
                    mostrarMensaje("No hay vencimientos para este RUC");
                } else {
                    lb_ene.setText("Ene-" + año + ":");
                    lb_feb.setText("Feb-" + año + ":");
                    lb_mar.setText("Mar-" + año + ":");
                    lb_abr.setText("Abr-" + año + ":");
                    lb_may.setText("May-" + año + ":");
                    lb_jun.setText("Jun-" + año + ":");
                    lb_jul.setText("Jul-" + año + ":");
                    lb_ago.setText("Ago-" + año + ":");
                    lb_set.setText("Set-" + año + ":");
                    lb_oct.setText("Oct-" + año + ":");
                    lb_nov.setText("Nov-" + año + ":");
                    lb_dic.setText("Dic-" + año + ":");
                    if (tipo.equalsIgnoreCase("IMPUESTOS")) {
                        txt_ene.setText(v.getEnero());
                        txt_feb.setText(v.getFebrero());
                        txt_mar.setText(v.getMarzo());
                        txt_abr.setText(v.getAbril());
                        txt_may.setText(v.getMayo());
                        txt_jun.setText(v.getJunio());
                        txt_jul.setText(v.getJulio());
                        txt_ago.setText(v.getAgosto());
                        txt_set.setText(v.getSeptiembre());
                        txt_oct.setText(v.getOctubre());
                        txt_nov.setText(v.getNoviembre());
                        txt_dic.setText(v.getDiciembre());
                    } else if (tipo.equalsIgnoreCase("PLE")) {
                        PLE ple = v.getPle();
                        txt_ene.setText(ple.getEnero());
                        txt_feb.setText(ple.getFebrero());
                        txt_mar.setText(ple.getMarzo());
                        txt_abr.setText(ple.getAbril());
                        txt_may.setText(ple.getMayo());
                        txt_jun.setText(ple.getJunio());
                        txt_jul.setText(ple.getJulio());
                        txt_ago.setText(ple.getAgosto());
                        txt_set.setText(ple.getSeptiembre());
                        txt_oct.setText(ple.getOctubre());
                        txt_nov.setText(ple.getNoviembre());
                        txt_dic.setText(ple.getDiciembre());
                    } else if (tipo.equalsIgnoreCase("AMBOS")) {
                        PLE ple = v.getPle();
                        txt_ene.setText("Impto: " + v.getEnero() + " / PLE: " + ple.getEnero());
                        txt_feb.setText("Impto: " + v.getFebrero() + " / PLE: " + ple.getFebrero());
                        txt_mar.setText("Impto: " + v.getMarzo() + " / PLE: " + ple.getMarzo());
                        txt_abr.setText("Impto: " + v.getAbril() + " / PLE: " + ple.getAbril());
                        txt_may.setText("Impto: " + v.getMayo() + " / PLE: " + ple.getMayo());
                        txt_jun.setText("Impto: " + v.getJunio() + " / PLE: " + ple.getJunio());
                        txt_jul.setText("Impto: " + v.getJulio() + " / PLE: " + ple.getJulio());
                        txt_ago.setText("Impto: " + v.getAgosto() + " / PLE: " + ple.getAgosto());
                        txt_set.setText("Impto: " + v.getSeptiembre() + " / PLE: " + ple.getSeptiembre());
                        txt_oct.setText("Impto: " + v.getOctubre() + " / PLE: " + ple.getOctubre());
                        txt_nov.setText("Impto: " + v.getNoviembre() + " / PLE: " + ple.getNoviembre());
                        txt_dic.setText("Impto: " + v.getDiciembre() + " / PLE: " + ple.getDiciembre());
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al buscar al cliente",
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_ruc.setText("");
        this.idCliente = 0;
        //TXT´s
        txt_ene.setText(txt_ene.getName());
        txt_feb.setText(txt_feb.getName());
        txt_mar.setText(txt_mar.getName());
        txt_abr.setText(txt_abr.getName());
        txt_may.setText(txt_may.getName());
        txt_jun.setText(txt_jun.getName());
        txt_jul.setText(txt_jul.getName());
        txt_ago.setText(txt_ago.getName());
        txt_set.setText(txt_set.getName());
        txt_oct.setText(txt_oct.getName());
        txt_nov.setText(txt_nov.getName());
        txt_dic.setText(txt_dic.getName());
        //LABELS
        lb_ene.setText("Ene-20** :");
        lb_feb.setText("Feb-20** :");
        lb_mar.setText("Mar-20** :");
        lb_abr.setText("Abr-20** :");
        lb_may.setText("May-20** :");
        lb_jun.setText("Jun-20** :");
        lb_jul.setText("Jul-20** :");
        lb_ago.setText("Ago-20** :");
        lb_set.setText("Set-20** :");
        lb_oct.setText("Oct-20** :");
        lb_nov.setText("Nov-20** :");
        lb_dic.setText("Dic-20** :");
        //OTHERS
        txt_ruc.requestFocus();
        año_select.setValue(2026);
        venc_box.setSelectedIndex(0);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        PageFormat pageFormat = printerJob.defaultPage();
        pageFormat.setOrientation(PageFormat.LANDSCAPE);
        printerJob.setPrintable((graphics, pf, pageIndex) -> {
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate(
                    pageFormat.getImageableX(),
                    pageFormat.getImageableY()
            );
            double scaleX = pageFormat.getImageableWidth() / pnl_print.getWidth();
            double scaleY = pageFormat.getImageableHeight() / pnl_print.getHeight();
            double scale = Math.min(scaleX, scaleY);
            g2d.scale(scale, scale);
            pnl_print.printAll(g2d);
            return Printable.PAGE_EXISTS;
        }, pageFormat);
        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void venc_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venc_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venc_boxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser año_select;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_print;
    private javax.swing.JLabel lb_abr;
    private javax.swing.JLabel lb_ago;
    private javax.swing.JLabel lb_dic;
    private javax.swing.JLabel lb_ene;
    private javax.swing.JLabel lb_feb;
    private javax.swing.JLabel lb_jul;
    private javax.swing.JLabel lb_jun;
    private javax.swing.JLabel lb_mar;
    private javax.swing.JLabel lb_may;
    private javax.swing.JLabel lb_nov;
    private javax.swing.JLabel lb_oct;
    private javax.swing.JLabel lb_ruc;
    private javax.swing.JLabel lb_set;
    private javax.swing.JPanel pnl_abr;
    private javax.swing.JPanel pnl_action;
    private javax.swing.JPanel pnl_ago;
    private javax.swing.JPanel pnl_dic;
    private javax.swing.JPanel pnl_ene;
    private javax.swing.JPanel pnl_feb;
    private javax.swing.JPanel pnl_jul;
    private javax.swing.JPanel pnl_jun;
    private javax.swing.JPanel pnl_mar;
    private javax.swing.JPanel pnl_may;
    private javax.swing.JPanel pnl_nov;
    private javax.swing.JPanel pnl_oct;
    private javax.swing.JPanel pnl_print;
    private javax.swing.JPanel pnl_sep;
    private javax.swing.JLabel txt_abr;
    private javax.swing.JLabel txt_ago;
    private javax.swing.JLabel txt_dic;
    private javax.swing.JLabel txt_ene;
    private javax.swing.JLabel txt_feb;
    private javax.swing.JLabel txt_jul;
    private javax.swing.JLabel txt_jun;
    private javax.swing.JLabel txt_mar;
    private javax.swing.JLabel txt_may;
    private javax.swing.JLabel txt_nov;
    private javax.swing.JLabel txt_oct;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JLabel txt_set;
    private javax.swing.JComboBox<String> venc_box;
    // End of variables declaration//GEN-END:variables
}
