package com.sistema_contable.vista.general;

import com.sistema_contable.model.Vencimientos;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class ResultadoBusqueda extends javax.swing.JDialog {

    
    public ResultadoBusqueda(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
    }
    
    public ResultadoBusqueda(
            java.awt.Frame parent,
            boolean modal,
            List<Vencimientos> lista,
            String mes,
            int año,
            String periodo
    ) {
        super(parent, modal);
        initComponents();
        txt_periodo.setEditable(false);
        txt_periodo.setText(periodo);
        setTitle("Resultados - " + mes + " " + año);
        DefaultTableModel model = (DefaultTableModel) tbl_general.getModel();
        model.setRowCount(0);
        for (Vencimientos v : lista) {
            model.addRow(new Object[]{
                v.getCliente().getNombre(),
                v.getCliente().getRUC(),
                v.getVencimiento(),
                v.getPle().getVencimiento_ple()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_print = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_general = new javax.swing.JTable();
        txt_periodo = new javax.swing.JTextField();
        lb_periodo = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_print.setBackground(new java.awt.Color(204, 204, 204));

        tbl_general.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbl_general.setForeground(new java.awt.Color(0, 0, 0));
        tbl_general.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CLIENTE", "RUC", "VENCIMIENTO", "PLE"
            }
        ));
        jScrollPane1.setViewportView(tbl_general);
        if (tbl_general.getColumnModel().getColumnCount() > 0) {
            tbl_general.getColumnModel().getColumn(0).setMaxWidth(500);
            tbl_general.getColumnModel().getColumn(1).setMaxWidth(120);
            tbl_general.getColumnModel().getColumn(2).setMaxWidth(82);
            tbl_general.getColumnModel().getColumn(3).setMaxWidth(82);
        }

        txt_periodo.setBackground(new java.awt.Color(255, 255, 255));
        txt_periodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lb_periodo.setBackground(new java.awt.Color(204, 204, 204));
        lb_periodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_periodo.setForeground(new java.awt.Color(0, 0, 0));
        lb_periodo.setText("Periodo:");

        btn_print.setBackground(new java.awt.Color(102, 102, 102));
        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_print.setForeground(new java.awt.Color(0, 0, 0));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora .png"))); // NOI18N
        btn_print.setText("Imprimir");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_excel.setBackground(new java.awt.Color(1, 115, 64));
        btn_excel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_excel.setForeground(new java.awt.Color(255, 255, 255));
        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        btn_excel.setText("Excel");
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_printLayout = new javax.swing.GroupLayout(pnl_print);
        pnl_print.setLayout(pnl_printLayout);
        pnl_printLayout.setHorizontalGroup(
            pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_printLayout.createSequentialGroup()
                .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_printLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lb_periodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_print)
                        .addGap(57, 57, 57)
                        .addComponent(btn_excel))
                    .addGroup(pnl_printLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnl_printLayout.setVerticalGroup(
            pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_printLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_periodo)
                    .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print)
                    .addComponent(btn_excel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        try {
            String periodo = txt_periodo.getText().trim();
            MessageFormat header = new MessageFormat("Periodo: " + periodo);
            MessageFormat footer = new MessageFormat("Página {0}");
            tbl_general.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
        try {
            // ================= FILECHOOSER =================
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Guardar Excel");
            chooser.setSelectedFile(new File("Cronograma.xlsx"));
            if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
                return;
            }
            File file = chooser.getSelectedFile();
            String path = file.getAbsolutePath();
            if (!path.toLowerCase().endsWith(".xlsx")) {
                path += ".xlsx";
            }
            // ================= PERIODO =================
            int year = obtenerAño(txt_periodo.getText()); // puedes hacerlo dinámico
            if (year == -1) {
                JOptionPane.showMessageDialog(null, "Año invalido");
                return;
            }
            String periodoExcel = periodo_Excel(txt_periodo.getText(), year);
            if (periodoExcel == null) {
                JOptionPane.showMessageDialog(null, "Periodo inválido");
                return;
            }
            TableModel model = tbl_general.getModel();
            // ================= WORKBOOK =================
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Cronograma");
            int startRow = 0;
            int totalCols = model.getColumnCount() + 4; // A,B + tabla + G,H
            // ================= ESTILOS =================
            CellStyle borderStyle = workbook.createCellStyle();
            borderStyle.setBorderTop(BorderStyle.THIN);
            borderStyle.setBorderBottom(BorderStyle.THIN);
            borderStyle.setBorderLeft(BorderStyle.THIN);
            borderStyle.setBorderRight(BorderStyle.THIN);
            // ---- TITULO ----
            CellStyle titleStyle = workbook.createCellStyle();
            titleStyle.cloneStyleFrom(borderStyle);
            titleStyle.setAlignment(HorizontalAlignment.CENTER);
            titleStyle.setVerticalAlignment(VerticalAlignment.CENTER);
            XSSFFont titleFont = workbook.createFont();
            titleFont.setBold(true);
            titleFont.setFontHeightInPoints((short) 13);
            titleStyle.setFont(titleFont);
            // ---- ENCABEZADOS ----
            CellStyle headerStyle = workbook.createCellStyle();
            headerStyle.cloneStyleFrom(borderStyle);
            headerStyle.setAlignment(HorizontalAlignment.CENTER);
            XSSFFont headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerStyle.setFont(headerFont);
            // ---- CENTRADO ----
            CellStyle centerStyle = workbook.createCellStyle();
            centerStyle.cloneStyleFrom(borderStyle);
            centerStyle.setAlignment(HorizontalAlignment.CENTER);
            // ================= TITULO =================
            Row titleRow = sheet.createRow(startRow);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue("CRONOGRAMA DE VENCIMIENTO MENSUAL (PERIODO: " + periodoExcel + ")");
            titleCell.setCellStyle(titleStyle);
            // Merge de A hasta H
            sheet.addMergedRegion(
                new CellRangeAddress(startRow, startRow, 0, totalCols - 1)
            );
            // Aplicar estilo a toda la fila del título
            for (int c = 0; c < totalCols; c++) {
                Cell cell = titleRow.getCell(c);
                if (cell == null) {
                    cell = titleRow.createCell(c);
                }
                cell.setCellStyle(titleStyle);
            }
            // ================= ENCABEZADOS =================
            Row headerRow = sheet.createRow(startRow + 1);
            // Columnas A y B vacías con borde
            for (int c = 0; c < 2; c++) {
                Cell cell = headerRow.createCell(c);
                cell.setCellStyle(borderStyle);
            }
            // Encabezados reales del JTable
            for (int col = 0; col < model.getColumnCount(); col++) {
                Cell cell = headerRow.createCell(col + 2);
                cell.setCellValue(model.getColumnName(col));
                cell.setCellStyle(headerStyle);
            }
            // Columnas G y H vacías con borde
            for (int c = model.getColumnCount() + 2; c < totalCols; c++) {
                Cell cell = headerRow.createCell(c);
                cell.setCellStyle(borderStyle);
            }
            // ================= DATOS =================
            for (int row = 0; row < model.getRowCount(); row++) {
                Row excelRow = sheet.createRow(startRow + 2 + row);
                // Columnas A y B vacías con borde
                for (int c = 0; c < 2; c++) {
                    Cell cell = excelRow.createCell(c);
                    cell.setCellStyle(borderStyle);
                }
                // Datos del JTable
                for (int col = 0; col < model.getColumnCount(); col++) {
                    Cell cell = excelRow.createCell(col + 2);
                    Object value = model.getValueAt(row, col);
                    if (value != null) {
                        cell.setCellValue(value.toString());
                    }
                    if (model.getColumnName(col).equalsIgnoreCase("Vencimiento")) {
                        cell.setCellStyle(centerStyle);
                    } else {
                        cell.setCellStyle(borderStyle);
                    }
                }
                // Columnas G y H vacías con borde
                for (int c = model.getColumnCount() + 2; c < totalCols; c++) {
                    Cell cell = excelRow.createCell(c);
                    cell.setCellStyle(borderStyle);
                }
            }
            // ================= AUTO SIZE =================
            for (int c = 0; c < totalCols; c++) {
                sheet.autoSizeColumn(c);
            }
            // ================= GUARDAR =================
            try (FileOutputStream out = new FileOutputStream(path)) {
                workbook.write(out);
            }
            workbook.close();
            JOptionPane.showMessageDialog(null, "Excel generado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al exportar a Excel", "ERROR", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_excelActionPerformed

    private String periodo_Excel(String textoPeriodo, int year) {
        String mes_complet = obtenerMes(textoPeriodo);
        if (mes_complet == null) {
            return null;
        }
        String mes_excel;
        switch (mes_complet) {
            case "enero":
                mes_excel = "Ene";
                break;
            case "febrero":
                mes_excel = "Feb";
                break;
            case "marzo":
                mes_excel = "Mar";
                break;
            case "abril":
                mes_excel = "Abr";
                break;
            case "mayo":
                mes_excel = "May";
                break;
            case "junio":
                mes_excel = "Jun";
                break;
            case "julio":
                mes_excel = "Jul";
                break;
            case "agosto":
                mes_excel = "Ago";
                break;
            case "septiembre":
                mes_excel = "Sep";
                break;
            case "octubre":
                mes_excel = "Oct";
                break;
            case "noviembre":
                mes_excel = "Nov";
                break;
            case "diciembre":
                mes_excel = "Dic";
                break;
            default:
                return null;
        }
        return mes_excel + "-" + year;
    }
    
    private String obtenerMes(String mes) {
        if (mes == null || mes.length() < 3) {
            return null;
        }
        mes = mes.substring(0, 3).toLowerCase();
        if (mes.equals("ene")) {
            return "enero";
        } else if (mes.equals("feb")) {
            return "febrero";
        } else if (mes.equals("mar")) {
            return "marzo";
        } else if (mes.equals("abr")) {
            return "abril";
        } else if (mes.equals("may")) {
            return "mayo";
        } else if (mes.equals("jun")) {
            return "junio";
        } else if (mes.equals("jul")) {
            return "julio";
        } else if (mes.equals("ago")) {
            return "agosto";
        } else if (mes.equals("sep")) {
            return "septiembre";
        } else if (mes.equals("oct")) {
            return "octubre";
        } else if (mes.equals("nov")) {
            return "noviembre";
        } else if (mes.equals("dic")) {
            return "diciembre";
        } else {
            return null;
        }
    }
    
    private int obtenerAño(String periodo) {
        String numeros = periodo.replaceAll("\\D", "");
        if (numeros.length() == 4) {
            return Integer.parseInt(numeros);
        }
        return -1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultadoBusqueda dialog = new ResultadoBusqueda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_print;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_periodo;
    private javax.swing.JPanel pnl_print;
    private javax.swing.JTable tbl_general;
    private javax.swing.JTextField txt_periodo;
    // End of variables declaration//GEN-END:variables
}
